#pragma once

#include <SDL3/SDL.h>

// Compatibility aliases so existing call sites keep GLFW-style names while
// keys are actually SDL scancodes. Mouse buttons stay 0-based like GLFW.
#ifndef GLFW_PRESS
#define GLFW_PRESS 1
#endif
#ifndef GLFW_RELEASE
#define GLFW_RELEASE 0
#endif

#ifndef GLFW_CURSOR_NORMAL
#define GLFW_CURSOR_NORMAL 0
#endif
#ifndef GLFW_CURSOR_DISABLED
#define GLFW_CURSOR_DISABLED 1
#endif
#ifndef GLFW_CURSOR
#define GLFW_CURSOR 0x00033001
#endif

#ifndef GLFW_MOUSE_BUTTON_LEFT
#define GLFW_MOUSE_BUTTON_LEFT 0
#define GLFW_MOUSE_BUTTON_RIGHT 1
#define GLFW_MOUSE_BUTTON_MIDDLE 2
#define GLFW_MOUSE_BUTTON_LAST 7
#endif

#ifndef GLFW_KEY_LAST
#define GLFW_KEY_SPACE SDL_SCANCODE_SPACE
#define GLFW_KEY_APOSTROPHE SDL_SCANCODE_APOSTROPHE
#define GLFW_KEY_COMMA SDL_SCANCODE_COMMA
#define GLFW_KEY_MINUS SDL_SCANCODE_MINUS
#define GLFW_KEY_PERIOD SDL_SCANCODE_PERIOD
#define GLFW_KEY_SLASH SDL_SCANCODE_SLASH
#define GLFW_KEY_0 SDL_SCANCODE_0
#define GLFW_KEY_1 SDL_SCANCODE_1
#define GLFW_KEY_2 SDL_SCANCODE_2
#define GLFW_KEY_3 SDL_SCANCODE_3
#define GLFW_KEY_4 SDL_SCANCODE_4
#define GLFW_KEY_5 SDL_SCANCODE_5
#define GLFW_KEY_6 SDL_SCANCODE_6
#define GLFW_KEY_7 SDL_SCANCODE_7
#define GLFW_KEY_8 SDL_SCANCODE_8
#define GLFW_KEY_9 SDL_SCANCODE_9
#define GLFW_KEY_SEMICOLON SDL_SCANCODE_SEMICOLON
#define GLFW_KEY_EQUAL SDL_SCANCODE_EQUALS
#define GLFW_KEY_A SDL_SCANCODE_A
#define GLFW_KEY_B SDL_SCANCODE_B
#define GLFW_KEY_C SDL_SCANCODE_C
#define GLFW_KEY_D SDL_SCANCODE_D
#define GLFW_KEY_E SDL_SCANCODE_E
#define GLFW_KEY_F SDL_SCANCODE_F
#define GLFW_KEY_G SDL_SCANCODE_G
#define GLFW_KEY_H SDL_SCANCODE_H
#define GLFW_KEY_I SDL_SCANCODE_I
#define GLFW_KEY_J SDL_SCANCODE_J
#define GLFW_KEY_K SDL_SCANCODE_K
#define GLFW_KEY_L SDL_SCANCODE_L
#define GLFW_KEY_M SDL_SCANCODE_M
#define GLFW_KEY_N SDL_SCANCODE_N
#define GLFW_KEY_O SDL_SCANCODE_O
#define GLFW_KEY_P SDL_SCANCODE_P
#define GLFW_KEY_Q SDL_SCANCODE_Q
#define GLFW_KEY_R SDL_SCANCODE_R
#define GLFW_KEY_S SDL_SCANCODE_S
#define GLFW_KEY_T SDL_SCANCODE_T
#define GLFW_KEY_U SDL_SCANCODE_U
#define GLFW_KEY_V SDL_SCANCODE_V
#define GLFW_KEY_W SDL_SCANCODE_W
#define GLFW_KEY_X SDL_SCANCODE_X
#define GLFW_KEY_Y SDL_SCANCODE_Y
#define GLFW_KEY_Z SDL_SCANCODE_Z
#define GLFW_KEY_ESCAPE SDL_SCANCODE_ESCAPE
#define GLFW_KEY_ENTER SDL_SCANCODE_RETURN
#define GLFW_KEY_TAB SDL_SCANCODE_TAB
#define GLFW_KEY_BACKSPACE SDL_SCANCODE_BACKSPACE
#define GLFW_KEY_INSERT SDL_SCANCODE_INSERT
#define GLFW_KEY_DELETE SDL_SCANCODE_DELETE
#define GLFW_KEY_RIGHT SDL_SCANCODE_RIGHT
#define GLFW_KEY_LEFT SDL_SCANCODE_LEFT
#define GLFW_KEY_DOWN SDL_SCANCODE_DOWN
#define GLFW_KEY_UP SDL_SCANCODE_UP
#define GLFW_KEY_PAGE_UP SDL_SCANCODE_PAGEUP
#define GLFW_KEY_PAGE_DOWN SDL_SCANCODE_PAGEDOWN
#define GLFW_KEY_HOME SDL_SCANCODE_HOME
#define GLFW_KEY_END SDL_SCANCODE_END
#define GLFW_KEY_CAPS_LOCK SDL_SCANCODE_CAPSLOCK
#define GLFW_KEY_SCROLL_LOCK SDL_SCANCODE_SCROLLLOCK
#define GLFW_KEY_NUM_LOCK SDL_SCANCODE_NUMLOCKCLEAR
#define GLFW_KEY_PRINT_SCREEN SDL_SCANCODE_PRINTSCREEN
#define GLFW_KEY_PAUSE SDL_SCANCODE_PAUSE
#define GLFW_KEY_F1 SDL_SCANCODE_F1
#define GLFW_KEY_F2 SDL_SCANCODE_F2
#define GLFW_KEY_F3 SDL_SCANCODE_F3
#define GLFW_KEY_F4 SDL_SCANCODE_F4
#define GLFW_KEY_F5 SDL_SCANCODE_F5
#define GLFW_KEY_F6 SDL_SCANCODE_F6
#define GLFW_KEY_F7 SDL_SCANCODE_F7
#define GLFW_KEY_F8 SDL_SCANCODE_F8
#define GLFW_KEY_F9 SDL_SCANCODE_F9
#define GLFW_KEY_F10 SDL_SCANCODE_F10
#define GLFW_KEY_F11 SDL_SCANCODE_F11
#define GLFW_KEY_F12 SDL_SCANCODE_F12
#define GLFW_KEY_KP_0 SDL_SCANCODE_KP_0
#define GLFW_KEY_KP_1 SDL_SCANCODE_KP_1
#define GLFW_KEY_KP_2 SDL_SCANCODE_KP_2
#define GLFW_KEY_KP_3 SDL_SCANCODE_KP_3
#define GLFW_KEY_KP_4 SDL_SCANCODE_KP_4
#define GLFW_KEY_KP_5 SDL_SCANCODE_KP_5
#define GLFW_KEY_KP_6 SDL_SCANCODE_KP_6
#define GLFW_KEY_KP_7 SDL_SCANCODE_KP_7
#define GLFW_KEY_KP_8 SDL_SCANCODE_KP_8
#define GLFW_KEY_KP_9 SDL_SCANCODE_KP_9
#define GLFW_KEY_KP_ENTER SDL_SCANCODE_KP_ENTER
#define GLFW_KEY_LEFT_SHIFT SDL_SCANCODE_LSHIFT
#define GLFW_KEY_LEFT_CONTROL SDL_SCANCODE_LCTRL
#define GLFW_KEY_LEFT_ALT SDL_SCANCODE_LALT
#define GLFW_KEY_RIGHT_SHIFT SDL_SCANCODE_RSHIFT
#define GLFW_KEY_RIGHT_CONTROL SDL_SCANCODE_RCTRL
#define GLFW_KEY_RIGHT_ALT SDL_SCANCODE_RALT
#define GLFW_KEY_GRAVE_ACCENT SDL_SCANCODE_GRAVE
#define GLFW_KEY_LAST (SDL_SCANCODE_COUNT - 1)
#endif
